# Generated by Django 4.2.30 on 2026-05-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('svd', 'SVD'), ('tfidf', 'TF-IDF')], max_length=10)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('precision_at_k', models.FloatField(blank=True, null=True)),
                ('recall_at_k', models.FloatField(blank=True, null=True)),
                ('coverage', models.FloatField(blank=True, null=True)),
                ('diversity', models.FloatField(blank=True, null=True)),
                ('k_value', models.IntegerField(default=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('cf_score', models.FloatField(default=0.0)),
                ('cbf_score', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('hybrid', 'Hybrid'), ('collaborative', 'Collaborative Only'), ('content', 'Content-Based Only'), ('trending', 'Trending')], max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('alpha_used', models.FloatField(default=0.5)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.product')),
            ],
        ),
    ]
