# Generated by Django 4.2.30 on 2026-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
